---
- name: Apply Updates
  strategy: free
  hosts: all
  serial: '25%'
  max_fail_percentage: 20
  tasks:
    - name: Run prepatching process
      import_role:
        name: prepatch_script

    - name: Grab uuid for host 
      import_role:
        name: gather_uuid

    - name: Sleep task while snapshot completes
      import_role:
        name: snapshot_sleep

    - name: Make sure system is correctly subscribed
      import_role:
        name: subscription
    
    - name: Shutdown server
      import_role:
        name: shutdown_host
    
    - name: Power on guest
      import_role:
       name: poweron_vm
