---
- name: Get Subscription Variables
  include_vars: '{{ aaa_environment }}.yml'

- name: Subscription based on Production
  redhat_subscription:
    state: present
    activationkey: '{{ sat_activation_key }}'
    org_id: '{{ sat_org_id }}'
    autosubscribe: yes
    force_register: yes 
