---
- name: Subscription based on Production
  tags:
    - Production
  redhat_subscription:
    state: present
    activationkey: RHEL7_AK
    org_id: Rydzinski
    autosubscribe: yes
    force_register: yes

- name: Subscription based on Developement
  tags:
    - Developement
  redhat_subscription:
    state: present
    activationkey: stage_ak
    org_id: Rydzinski
    autosubscribe: yes
    force_register: yes
