---
- name: copy script from remote host
  copy:
   src: prepatch_script.sh
   dest: /root/prepatch_script.sh
   mode: 0755

- name: excute the script
  command: sh /root/prepatch_script.sh

- name: Slurp the file
  slurp:
     src: /tmp/Before_Patching.txt
  register: testfile_content

- name: Put the file on a non-inventory host
  copy:
    content: "{{ testfile_content['content'] | b64decode }}"
    dest: /root/Before_Patching_{{ ansible_hostname }}.txt
  delegate_to: 192.168.5.141
